Help page
just1ngray/CSCI3428 pull request #66
Opened 2020-11-23 04:00 UTC by ynaffit96

All accordions closed:
![Screenshot (7)](https://user-images.githubusercontent.com/71397219/99928084-09b41e00-2d1e-11eb-84f4-dc42d1a652e0.png)
Showing only one opened:
![Screenshot (8)](https://user-images.githubusercontent.com/71397219/99928085-09b41e00-2d1e-11eb-88b9-ab03e515e38b.png)
All can be open at the same time:
![Screenshot (9)](https://user-images.githubusercontent.com/71397219/99928086-0a4cb480-2d1e-11eb-8fad-dd1909a311cd.png)

2020-11-23 23:57 UTC, just1ngray requested changes
Two very quick things before we merge:
1. Delete your commit to `_app.js` since we don't need to import a css module like that.
2. Make sure you format with `Prettier` before committing!

You don't need to make a new pull request.
```
git checkout helpPage
git pull
> Make your modifications
git commit (FILE) or commit via VS Code's GitHub controller
git push or push via VS Code's GitHub cloud icon
```
Then boom! This pull request will have changes!

2020-11-23 23:57 UTC, just1ngray commented on client/pages/_app.js
> +import "../styles/Accordion.module.css"
CSS Modules shouldn't be imported globally (unless they have global marked classes, I think marked with `:`).
You should be able to delete this addition 👍

2020-11-23 23:59 UTC, just1ngray commented
Whoops, and I just noticed this will merge into `master` and not `development`. Maybe you can change it? Otherwise could you please finish my requested changes and then make a new PR into `development`?

Thank ya!

2020-11-24 00:18 UTC, ynaffit96 commented
Okay I think it's good to go now!

2020-11-24 00:25 UTC, ynaffit96 commented
NEVERMIND I forgot to use prettier -_-

2020-11-24 00:37 UTC, just1ngray approved these changes
Sweet! 🥇

2020-11-24 00:37 UTC, merged